export const featureComparison = [
  {
    category: "Matters & Clients",
    features: [
      {
        name: "Active matters",
        free: "5",
        solo: "Unlimited",
        firm: "Unlimited",
        enterprise: "Unlimited",
      },
      {
        name: "Client profiles",
        free: "10",
        solo: "Unlimited",
        firm: "Unlimited",
        enterprise: "Unlimited",
      },
      {
        name: "Client portal",
        free: false,
        solo: true,
        firm: true,
        enterprise: true,
      },
      {
        name: "Matter templates",
        free: false,
        solo: true,
        firm: true,
        enterprise: true,
      },
      {
        name: "Custom fields",
        free: false,
        solo: true,
        firm: true,
        enterprise: true,
      },
    ],
  },
  {
    category: "Documents",
    features: [
      {
        name: "Storage",
        free: "1 GB",
        solo: "10 GB",
        firm: "100 GB",
        enterprise: "Unlimited",
      },
      {
        name: "Document templates",
        free: "3",
        solo: "Unlimited",
        firm: "Unlimited",
        enterprise: "Unlimited",
      },
      {
        name: "E-signatures",
        free: false,
        solo: true,
        firm: true,
        enterprise: true,
      },
      {
        name: "Version history",
        free: false,
        solo: "30 days",
        firm: "1 year",
        enterprise: "Unlimited",
      },
      {
        name: "Advanced search",
        free: false,
        solo: true,
        firm: true,
        enterprise: true,
      },
    ],
  },
  {
    category: "Time & Billing",
    features: [
      {
        name: "Time tracking",
        free: "Basic",
        solo: true,
        firm: true,
        enterprise: true,
      },
      {
        name: "Invoicing",
        free: false,
        solo: true,
        firm: true,
        enterprise: true,
      },
      {
        name: "Online payments",
        free: false,
        solo: true,
        firm: true,
        enterprise: true,
      },
      {
        name: "Expense tracking",
        free: false,
        solo: true,
        firm: true,
        enterprise: true,
      },
      {
        name: "Trust accounting",
        free: false,
        solo: false,
        firm: true,
        enterprise: true,
      },
      {
        name: "Financial reports",
        free: false,
        solo: "Basic",
        firm: "Advanced",
        enterprise: "Custom",
      },
    ],
  },
  {
    category: "Team & Collaboration",
    features: [
      {
        name: "Team members",
        free: "1",
        solo: "1",
        firm: "Unlimited",
        enterprise: "Unlimited",
      },
      {
        name: "Role permissions",
        free: false,
        solo: false,
        firm: true,
        enterprise: true,
      },
      {
        name: "Task assignments",
        free: false,
        solo: false,
        firm: true,
        enterprise: true,
      },
      {
        name: "Team calendar",
        free: false,
        solo: false,
        firm: true,
        enterprise: true,
      },
      {
        name: "Activity feed",
        free: false,
        solo: false,
        firm: true,
        enterprise: true,
      },
    ],
  },
  {
    category: "Security & Compliance",
    features: [
      {
        name: "Data encryption",
        free: true,
        solo: true,
        firm: true,
        enterprise: true,
      },
      {
        name: "Two-factor auth",
        free: true,
        solo: true,
        firm: true,
        enterprise: true,
      },
      {
        name: "Audit logs",
        free: false,
        solo: false,
        firm: true,
        enterprise: true,
      },
      {
        name: "SSO/SAML",
        free: false,
        solo: false,
        firm: false,
        enterprise: true,
      },
      {
        name: "Custom security policies",
        free: false,
        solo: false,
        firm: false,
        enterprise: true,
      },
      {
        name: "Compliance reports",
        free: false,
        solo: false,
        firm: false,
        enterprise: true,
      },
    ],
  },
  {
    category: "Support & Services",
    features: [
      {
        name: "Support",
        free: "Community",
        solo: "Email",
        firm: "Priority",
        enterprise: "Dedicated",
      },
      {
        name: "Onboarding",
        free: false,
        solo: "Self-serve",
        firm: "Guided",
        enterprise: "White-glove",
      },
      {
        name: "Training",
        free: false,
        solo: false,
        firm: "Group",
        enterprise: "Custom",
      },
      {
        name: "API access",
        free: false,
        solo: false,
        firm: false,
        enterprise: true,
      },
      {
        name: "Custom integrations",
        free: false,
        solo: false,
        firm: true,
        enterprise: true,
      },
    ],
  },
];
