export const plans = [
  {
    name: "Free",
    description: "For getting started",
    monthlyPrice: "$0",
    yearlyPrice: "$0",
    period: "/month",
    popular: false,
    features: [
      "Up to 5 matters",
      "1 user",
      "Document storage (1GB)",
      "Basic time tracking",
      "Community support",
      "Mobile app access",
    ],
    cta: "Get started",
    href: "/demo",
  },
  {
    name: "Solo",
    description: "For independent practitioners",
    monthlyPrice: "$49",
    yearlyPrice: "$39",
    period: "/month",
    popular: false,
    features: [
      "Unlimited matters",
      "Client portal",
      "Document storage (10GB)",
      "Time tracking & billing",
      "Email support",
      "Mobile app access",
    ],
    cta: "Start free trial",
    href: "/demo",
  },
  {
    name: "Firm",
    description: "For growing law firms",
    monthlyPrice: "$99",
    yearlyPrice: "$79",
    period: "/user/month",
    popular: true,
    features: [
      "Everything in Solo",
      "Unlimited team members",
      "Document storage (100GB)",
      "Team collaboration tools",
      "Workflow automation",
      "Firm analytics & reporting",
      "Priority support",
      "Custom integrations",
    ],
    cta: "Start free trial",
    href: "/demo",
  },
  {
    name: "Enterprise",
    description: "For large organizations",
    monthlyPrice: "Custom",
    yearlyPrice: "Custom",
    period: "",
    popular: false,
    features: [
      "Everything in Firm",
      "Unlimited storage",
      "SSO/SAML authentication",
      "Advanced security controls",
      "Dedicated success manager",
      "Custom SLA",
      "On-premise deployment option",
      "API access",
    ],
    cta: "Contact sales",
    href: "/demo",
  },
];
